AllCops:
  Include:
    - '**/config.ru'
    - '**/Rakefile'
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FileName:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
