language: ruby
sudo: false
services:
- redis
before_script:
- bundle exec rake db:test:prepare
cache: bundler
notifications:
  email: false
  slack:
    rooms:
      secure: Eh6zUQWwzaYMIfAJKpW3uNNuSE/xjEQCHamopoSjnh/C0JWkXiqD33LeiKsStq/vHjUFQU0rrabOsTBezRUjmYhGtGjRwr5yu628AkQq+/m3P62ki+A7yVqZqAlS4hPw4c13ICbjgKhtuaman58KnzYX33aDCHeU5dYXHGG0eq5xgHUTfFwRHBaHNskIYGX25jYltvm7T7N6jtrBZKKA3J/tN+T7+TwVNY9KorDvs0e9ATw1iYvBk9LS0P7DVDN4I3TBuL6msf+zcv/bFnDp8Pf/amZ7VE4xE0YnYJI/Oj4KWG9eAndd0UX/O//56E5Cd5uSKgkNZiCNBMu/+9Q6BHhqQlrJgnrk2wYecdYIrib+WkgGS67qCSa4NpjIdEthOKNjiNJxL+9HmSKnxLD75KPfJ6PRGqg1Us/sY6SSuA+CwkrJdfpemMewywI8QpiV7C90Wprh28YJGsaOslkHn9CVBMPruoZvM4qqbAtrGqTtJ/zDdqSk2viYAZf8OPVwNoacnfBKCmBg/Zr/75ws283zyEQBe1+wW6N4erufmh3djhSuW1ccn7y6djgeM1ZONzgfk+6enVBcN8upiyBlePCc23QddTpmIa8sSBCDNGgR6yON+zeejY/D4bLd8lX4IBQEjJ8ugVckZIH9cSBHBC1HdJOQIT+49teRjgiS9RA=
